require_relative 'input_render/base_render'
require_relative 'input_render/boolean_render'
require_relative 'input_render/select_render'
require_relative 'input_render/string_render'
require_relative 'input_render/text_render'
